version: '3.8'

services:
  server:
    build:
      context: .
      target: server_prod
    depends_on:
      - database
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:server"]
    environment:
      DB_HOST: database

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    command: ["npm", "run", "start:worker"]
    environment:
      DB_HOST: database

volumes:
  flag:
